name: Docker Image CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        cd backend
        touch .env
        echo 'GOOGLE_MAPS_API_KEY=${{ secrets.GMAPS_KEY }}' >> .env
        echo 'GEOAPIFY_API_KEY=${{ secrets.GEOAPIFY_KEY }}' >> .env
        echo 'MONGO_API_KEY=${{ secrets.MONGO_DB }}' >> .env
        cat .env
    - name: Set up Docker Buildx
      run: |
          cd backend
          docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t andyma937/scarpool .
          docker run --rm --privileged tonistiigi/binfmt --install all
          docker buildx create --use --name scarpool-builder --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
          docker buildx inspect scarpool-builder --bootstrap
      shell: bash
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        cd backend
        docker buildx use scarpool-builder
        docker buildx build --file Dockerfile --tag andyma937/scarpool --push .
      shell: bash
    - name: Create SSH key
      run: |
        cd backend
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > key.pem
        sudo chmod 400 key.pem
        ssh-keyscan -H "$IP" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_KEY: ${{secrets.SSH_KEY}}
        IP: ${{secrets.AWS_IP}}
    - name: Ssh into AWS EC2 and update docker container
      run: |
        cd backend
        ssh -i "key.pem" ubuntu@"$IP" sudo docker ps -a
        ssh -i "key.pem" ubuntu@"$IP" "sudo docker ps -a -q | xargs -I {} sudo docker stop {}"
        ssh -i "key.pem" ubuntu@"$IP" "sudo docker ps -a -q | xargs -I {} sudo docker rm {}"
        ssh -i "key.pem" ubuntu@"$IP" sudo docker pull andyma937/scarpool
        ssh -i "key.pem" ubuntu@"$IP" sudo docker run -d -p 8080:8080 andyma937/scarpool
      env:
        IP: ${{secrets.AWS_IP}}
